version: 1
services:
  # 1. IdeaHub Backend API
  - type: web
    name: ideahub-backend
    runtime: node
    plan: free
    root: innovate-hub-core/backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
      - key: CLIENT_URL
      - key: PORT
        value: "10000"

  # 2. Snapcart Socket Server
  - type: web
    name: snapcart-socket
    runtime: node
    plan: free
    root: innovate-hub-core/snapcart/socket
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NEXT_BASE_URL
      - key: PORT
        value: "10000"

  # 3. Snapcart Driver App (Next.js)
  - type: web
    name: snapcart-driver-app
    runtime: node
    plan: free
    root: innovate-hub-core/snapcart/frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
      - key: NEXTAUTH_SECRET
      - key: NEXTAUTH_URL
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: snapcart-socket
          property: url
